### ISSUE TITLE
documentation: what does it do, and what not? 

### ISSUE THREAD

**Issue by henzeb** [allysonsilva/laravel-artisan-domain-contexts#3]
I have been looking at this documentation for a while now, but I am still not sure what it does, and what it fixes. 'domain' is usually used for 'example.com', 'api.example.com', so I expected it to be some sort of Tenancy (https://tenancyforlaravel.com/) like package. But it looks more like something that gives you (more) control on what file to store where and what to execute. 

Could you explain a bit more in the documentation on what problem it should solve?

**Comment by allysonsilva** [comment]
Hi, thanks for asking, so here goes:

- Added a new ["Concepts"](https://github.com/allysonsilva/laravel-artisan-domain-contexts#concepts) section, to explain the terms of "Domain" and "Contexts".
- I believe you don't know some of the **concepts of DDD**, and that's why it caused you this confusion, more basically, what I'm trying to do is simplify the project organization, dividing the different "groups" of the business in the application, and in this division of folders/architecture, the question remains: "_How do I perform migrations for a certain group/context?_" or "_How do I execute or create the seeders only in a certain context/folder?_", in this case, this package proposes to answer these questions taking into account the "Custom" structure of the application.
- To create a structure based on business interests in the application, I recommend seeing the following [article](https://stitcher.io/blog/organise-by-domain) and [see also](https://stitcher.io/blog/laravel-beyond-crud-01-domain-oriented-laravel)
